# Generated by Django 5.1.3 on 2024-12-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userOrganization', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('payabler', 'Payabler'), ('buyer', 'Buyer'), ('storekeeper', 'Storekeeper'), ('supplier', 'Supplier'), ('clients', 'Clients')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
