# Generated by Django 5.1.3 on 2024-12-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_organization_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/avatar/user.png', upload_to='avatar/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
