# Generated by Django 5.1.3 on 2024-12-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('t_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tAccount.taccounts')),
            ],
        ),
    ]
